name = "CCNO"
uuid = "e2fc1aba-fec3-4373-8f9f-d63a30ec9339"
authors = ["Zoha Laraib <zlaraib@vols.utk.edu>"]
version = "0.0.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
DelimitedFiles = "1.9.1"
HDF5 = "0.17.2"
ITensors = "0.9.0"
julia = "1.11.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
