name: Deploy Documentation to GitHub Pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      
permissions:
  contents: write
  
env:
  JULIA_VERSION: '1.11.5'
  
jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ env.JULIA_VERSION }}
      - name: Install dependencies
        run: |
          julia --project=. -e 'import Pkg; Pkg.instantiate()'
      - name: Build the documentation
        run: |
          cd docs
          julia --project=.. make.jl
      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/build
          
  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download built docs
      uses: actions/download-artifact@v4
      with:
        name: docs-build
        path: docs/build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages  # The branch where the generated HTML will be deployed
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build  # The directory containing the generated HTML
        force_orphan: true  # remove branch history
